language: java

matrix:
  include:
    - os: linux
      arch: arm64
      jdk: openjdk11
      

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - libcppunit-dev

install:
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
     sudo apt-get install maven;
    fi

addons: 
    sonarcloud: 
        organization: ilcontecvma
        token: 
            0d06bb52fc32c7ffb68c7643165781ae525aeda6

script: 
    - mvn clean test
    - mvn sonar:sonar -Dsonar.projectKey=IlConteCvma_zookeeper -Dmaven.javadoc.skip=true
